// <auto-generated />
using BasicMVC.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicMVC.Migrations
{
    [DbContext(typeof(BasicDBContext))]
    partial class BasicDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BasicMVC.Models.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageID");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageID = 1,
                            MessageText = "Message one"
                        },
                        new
                        {
                            MessageID = 2,
                            MessageText = "Message Two"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
